### ISSUE TITLE
Uncaught TypeError: Cannot read property 'placeholder' of undefined 

### ISSUE THREAD

**Issue by sricc** [RobinBrouwer/gritter#37]
I'm getting this error when using rails 4.

http://www.screencast.com/t/UorNwmAS

Looks like it has something to do with Modernizr, so I'm not sure if this should be an issue here or in Modernizr, but it started when I installed gritter.  For some reason the Modernizr.input is not defined and there is no check to ensure it is.

Anything I can do to fix this?  I'd really like to use gritter.

Thanks.

**Comment by RobinBrouwer** [comment]
Fixed it in v1.2.0. I changed the Modernizr variable to GritterModernizr, so it doesn't change the Modernizr variable if you're using it inside your application.
