### ISSUE TITLE
Use Modernizr from asset pipeline instead of bundling it

### ISSUE THREAD

**Issue by betelgeuse** [RobinBrouwer/gritter#41]
https://github.com/RobinBrouwer/gritter/blob/0e800f5d68b8385081d10bee8962c49934d2e330/vendor/assets/javascripts/gritter.js

Now loading grittier replaces the global Modernizr object. Since this gem provides grittier for asset pipeline we should rather add a dependency on modernizr-rails and load the feature detection that way.

**Comment by RobinBrouwer** [comment]
Fixed it in v1.2.0. I changed the Modernizr variable to GritterModernizr, so it doesn't change the Modernizr if you're using it inside your application.
