### ISSUE TITLE
Undefined method gsub for :notice:Symbol

### ISSUE THREAD

**Issue by dtwconsulting** [RobinBrouwer/gritter#56]
I am trying to get gritter to work since I'd like to have nice, smooth notifications in my application.  I am rather new to rails and I am by no means an expert coder.  That said I do have an application up and running but I am struggling to get gritter working.

I am using rails 4.0.2 and ruby 1.9.3.  I would appreciate any help to get this working.  I saw the demo and it looks really nice.  I've tried to google for this error but could not find something that matches the issue I am having.

Here is what I have done:

Added the following to my gemfile:
gem 'gritter', '1.2.0'

Ran the following to create the locale file:
rails g gritter:locale

Added the following to my assets/javascripts/application.js file:
//= require gritter

Added the following to my assets/stylesheets/application.css file:
 *= require gritter

I created a new initializer file called gritter.erb and added the following line:
Gritter.rails_flash_fallback = true

Now, when I put a the following line into a controller, where a regular flash message used to be:
gflash :success => "This is a test notification"
I do get the notification but no real difference than the standard rails notification message.  

My next step is to place the line '<%= gflash %> into my application.html.erb file, as per the instructions.  This is when I get the following error message:
undefined method `gsub' for :notice:Symbol

The following is the full trace:
ctionpack (4.0.2) lib/action_view/helpers/javascript_helper.rb:27:in `escape_javascript'
gritter (1.2.0) lib/gritter/helpers.rb:20:in`add_gritter'
gritter (1.2.0) lib/gritter/helpers.rb:67:in `block (2 levels) in gflash'
gritter (1.2.0) lib/gritter/helpers.rb:59:in`each'
gritter (1.2.0) lib/gritter/helpers.rb:59:in `block in gflash'
gritter (1.2.0) lib/gritter/helpers.rb:57:in`each'
gritter (1.2.0) lib/gritter/helpers.rb:57:in `gflash'
app/views/layouts/application.html.erb:16:in`_app_views_layouts_application_html_erb__3071128289144318875_70348412631060'
actionpack (4.0.2) lib/action_view/template.rb:143:in `block in render'
activesupport (4.0.2) lib/active_support/notifications.rb:161:in`instrument'
actionpack (4.0.2) lib/action_view/template.rb:141:in `render'
actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:61:in`render_with_layout'
actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:17:in`render'
actionpack (4.0.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionpack (4.0.2) lib/action_view/renderer/renderer.rb:23:in`render'
actionpack (4.0.2) lib/abstract_controller/rendering.rb:127:in `_render_template'
actionpack (4.0.2) lib/action_controller/metal/streaming.rb:219:in`_render_template'
actionpack (4.0.2) lib/abstract_controller/rendering.rb:120:in `render_to_body'
actionpack (4.0.2) lib/action_controller/metal/rendering.rb:33:in`render_to_body'
actionpack (4.0.2) lib/action_controller/metal/renderers.rb:26:in `render_to_body'
actionpack (4.0.2) lib/abstract_controller/rendering.rb:97:in`render'
actionpack (4.0.2) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:41:in`block (2 levels) in render'
activesupport (4.0.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/dwilliams/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/benchmark.rb:295:in`realtime'
activesupport (4.0.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:41:in`block in render'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (4.0.2) lib/active_record/railties/controller_runtime.rb:25:in`cleanup_view_runtime'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:40:in `render'
actionpack (4.0.2) lib/action_controller/metal/implicit_render.rb:10:in`default_render'
actionpack (4.0.2) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.0.2) lib/abstract_controller/base.rb:189:in`process_action'
actionpack (4.0.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.0.2) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
activesupport (4.0.2) lib/active_support/callbacks.rb:433:in `_run__559863605771308521__process_action__callbacks'
activesupport (4.0.2) lib/active_support/callbacks.rb:80:in`run_callbacks'
actionpack (4.0.2) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (4.0.2) lib/action_controller/metal/rescue.rb:29:in`process_action'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.0.2) lib/active_support/notifications.rb:159:in`block in instrument'
activesupport (4.0.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.2) lib/active_support/notifications.rb:159:in`instrument'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.0.2) lib/action_controller/metal/params_wrapper.rb:245:in`process_action'
activerecord (4.0.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.0.2) lib/abstract_controller/base.rb:136:in`process'
actionpack (4.0.2) lib/abstract_controller/rendering.rb:44:in `process'
actionpack (4.0.2) lib/action_controller/metal.rb:195:in`dispatch'
actionpack (4.0.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.0.2) lib/action_controller/metal.rb:231:in`block in action'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:80:in`dispatch'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:71:in`block in call'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in`call'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:680:in `call'
rack (1.5.5) lib/rack/etag.rb:23:in`call'
rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.5) lib/rack/head.rb:11:in`call'
actionpack (4.0.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/flash.rb:241:in`call'
rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.5) lib/rack/session/abstract/id.rb:220:in`call'
actionpack (4.0.2) lib/action_dispatch/middleware/cookies.rb:486:in `call'
activerecord (4.0.2) lib/active_record/query_cache.rb:36:in`call'
activerecord (4.0.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
activerecord (4.0.2) lib/active_record/migration.rb:369:in`call'
actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.2) lib/active_support/callbacks.rb:373:in`_run__4234896245374213290__call__callbacks'
activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
actionpack (4.0.2) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/remote_ip.rb:76:in`call'
actionpack (4.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
railties (4.0.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.2) lib/rails/rack/logger.rb:20:in`block in call'
activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `block in tagged'
activesupport (4.0.2) lib/active_support/tagged_logging.rb:25:in`tagged'
activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `tagged'
railties (4.0.2) lib/rails/rack/logger.rb:20:in`call'
actionpack (4.0.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.5) lib/rack/methodoverride.rb:21:in`call'
rack (1.5.5) lib/rack/runtime.rb:17:in `call'
activesupport (4.0.2) lib/active_support/cache/strategy/local_cache.rb:83:in`call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/static.rb:64:in`call'
rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
railties (4.0.2) lib/rails/engine.rb:511:in`call'
railties (4.0.2) lib/rails/application.rb:97:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in`call'
rack (1.5.5) lib/rack/content_length.rb:14:in `call'
rack (1.5.5) lib/rack/handler/webrick.rb:60:in`service'
/home/dwilliams/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
/home/dwilliams/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/webrick/httpserver.rb:94:in`run'
/home/dwilliams/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

**Comment by RobinBrouwer** [comment]
I'm not sure why you're getting the error. It's saying something about a `:notice` Symbol, but you used `:success` as the key for the flash message. Weird. I just did the exact same thing as you (on Rails 4.0.2 and Ruby 1.9.3) and didn't get the error. Can't really help unless I see some more code. If you could send me a ZIP file of the project I could take a look.

**Comment by dtwconsulting** [comment]
Robin,

I've attached a few files for now to see if this is enough.  Please let me know.  
I really do appreciate any light you can shed on this to get this working.

---

Dave Williams

--------- Original Message --------- Subject: Re: [gritter] Undefined method gsub for :notice:Symbol (#56)

**Comment by RobinBrouwer** [comment]
Sorry, can't see anything wrong with the files you attached... You can send me the project via e-mail if you want, so I can take a closer look.

**Comment by dtwconsulting** [comment]
It appears to have been an issue with the browser I was using.  I develop in Kubuntu and the web browser I was using was Chromium Web Browser.  When I tried FF this worked fine :)

**Comment by RobinBrouwer** [comment]
Probably some kind of caching issue in the web browser. Great to hear it's working. :)
